server:
  port: 9003

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ncommerce
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ncommerce
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    name: order-topics
    partitions: 3
    replication-factor: 1

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8999/eureka
#        defaultZone: http://discovery-service:8999/eureka


