server:
  port: 9003

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ncommerce
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: order-service

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8999/eureka
#        defaultZone: http://discovery-service:8999/eureka