server:
  port: 8999

spring:
  application:
    name: service-discovery
eureka:
  client:
    register-with-eureka: false    # Do NOT register itself
    fetch-registry: false          # Do NOT fetch registry (no other servers)