version: '3.9'

services:
  service-discovery:
    build:
      context: ./service-discovery
    container_name: service-discovery
    ports:
      - "8999:8999"
    environment:
      - SPRING_PROFILES_ACTIVE=uat
    networks:
      - spring-net

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8998:8998"
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=uat
    networks:
      - spring-net

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "9002:9002"
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=uat
    networks:
      - spring-net

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "9003:9003"
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=uat
    networks:
      - spring-net

  # Optional: MongoDB
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - spring-net

  # Optional: PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: ncommerce
    ports:
      - "5432:5432"
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
